/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.ap2;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class FormControleDeVendas extends javax.swing.JFrame {
    ArrayList<Cliente> clientes = new ArrayList();
    ArrayList<Carro> carros = new ArrayList();
    ArrayList<Venda> vendas = new ArrayList();
    int contadorVendas = 1;
    
    /**
     * Creates new form FormControleDeVendas
     */
    public FormControleDeVendas() {
        initComponents();
        diretoNoCodigo();
    }
    public void diretoNoCodigo(){
        Cliente c1, c2, c3, c4;
        Carro cr1, cr2, cr3, cr4;
        Venda v1, v2;
        
        clientes.add(c1 = new Cliente("111", "Ana Banana", "1111-1111"));
        clientes.add(c2 = new Cliente("222", "Beto Bolado", "2222-2222"));
        clientes.add(c3 = new Cliente("333", "Carlos Cansado", "3333-3333"));
        clientes.add(c4 = new Cliente("444", "Denis Doidao", "4444-4444"));
        
        carros.add(cr1 = new Carro("1", "Placa1", "Hyundai", "HB20 ", "2021", "Branco, pouco tempo de uso, em perfeito estado", 40.000, false));
        carros.add(cr2 = new Carro("2", "Placa2", "Fiat ", "Uno ", "2010", "Cinza, tem escada no teto, porém precisa de uma bateria nova", 17.000, false));
        carros.add(cr3 = new Carro("3", "Placa3", "Fiat ", "Argo ", "2019", "Vermelho, precisa de um novo câmbio de marchas", 30.000, false));
        carros.add(cr4 = new Carro("4", "Placa4", "Chevrolet", "Onix  ", "2015", "Branco, necessita de reparos no motor", 27.000, false));
        
        vendas.add(v1 = new Venda(contadorVendas, c1, cr3));
        contadorVendas+=1;
        vendas.add(v2 = new Venda(contadorVendas, c2, cr4));       
        contadorVendas+=1;
        
        for (Cliente c : clientes){
            System.out.println(c.toString()+"\n");
         }    
         for (Carro cr : carros){
            System.out.println(cr.toString()+"\n");
         }    
          for (Venda v : vendas){
            System.out.println(v.toString()+"\n");
         }    
    }
    
      public Cliente existeCliente(String cliente){
      for (Cliente c : clientes){
            if (c.getNome().equalsIgnoreCase(cliente)){
                return c;
            } 
         } return null;
      } 
      
      public Carro existeCarro(String codigo){
      for (Carro cr : carros){
            if (cr.getCodigo().equalsIgnoreCase(codigo)){
                return cr;
            } 
         } return null;
      } 
             
     /* This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        tfVenda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfCliente = new javax.swing.JTextField();
        btCadastrarVenda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSaida = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfVendaActionPerformed(evt);
            }
        });

        jLabel2.setText("Cliente Comprador:");

        jLabel3.setText("Codigo do carro Vendido:");

        btCadastrarVenda.setText("Cadastrar Venda");
        btCadastrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarVendaActionPerformed(evt);
            }
        });

        taSaida.setColumns(20);
        taSaida.setRows(5);
        jScrollPane1.setViewportView(taSaida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(tfCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(btCadastrarVenda)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btCadastrarVenda)))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfVendaActionPerformed

    private void btCadastrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarVendaActionPerformed
        // TODO add your handling code here:        
        String clienteNovaVenda = tfCliente.getText();
        String codcarroNovaVenda = tfVenda.getText(); 
        
        if(tfCliente.getText().isBlank() || tfVenda.getText().isBlank()){
             JOptionPane.showMessageDialog(null, "Nenhum campo pode estar vazio!!!");
        }              
        else if (existeCliente(clienteNovaVenda) == null){
            JOptionPane.showMessageDialog(null, "Cliente não encontrado");           
        }   
        else if (existeCarro(codcarroNovaVenda) == null){
            JOptionPane.showMessageDialog(null, "Carro não encontrado");
        }   
        for(Carro c : carros){
            if(c.getCodigo().equals(codcarroNovaVenda)){
                 if(c.isFoiVendido() == true){
                     JOptionPane.showMessageDialog(null, "Esse carro já foi vendido");                     
                 }           
                 else if(existeCliente(clienteNovaVenda) == null){}
                 else{
                 vendas.add(new Venda(contadorVendas, existeCliente(clienteNovaVenda), c));
                 contadorVendas+=1;
                 taSaida.append("VENDA REALIZADA COM SUCESSO"+"\n");
                 Venda e = vendas.get(vendas.size() - 1);    
                 System.out.println(e.toString()+"\n");
                 }      
        }
        } 
        
    }//GEN-LAST:event_btCadastrarVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormControleDeVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormControleDeVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormControleDeVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormControleDeVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormControleDeVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrarVenda;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea taSaida;
    private javax.swing.JTextField tfCliente;
    private javax.swing.JTextField tfVenda;
    // End of variables declaration//GEN-END:variables
}
